name: destinosbrasil
version: '1.0.0'
config-version: 2

profile: destinosbrasil

model-paths:  ["models"]
seed-paths:   ["seeds"]
macro-paths:  ["macros"]

target-path:  "target"
clean-targets: ["target", "dbt_packages"]

models:
  destinosbrasil:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

seeds:
  destinosbrasil:
    +schema: staging
